### ISSUE TITLE
Need way to only build specific build(s) in a project

### ISSUE THREAD

**Issue by crossrulz** [jovianarts/LVSolutionBuilder#26]
This tool has helped a ton getting a project off the ground.  But now my project is in the state that I am only making small updates, usually only affecting 1 of the build specifications (currently 27 builds in this project, all PPLs).  What I need is a way to specify the specific build(s) that actually need built and only build those few instead of all of the build specifications.

**Comment by niphilj** [comment]
Hi @crossrulz , you're absolutely right. I was thinking of adding a way to do incremental builds which would only rebuild the pieces that need rebuilding.

**Comment by jovianarts** [comment]
Added incremental build support in 1.0.2
